<?php
/**
 * User:  jiangm
 * Email: jmphper@foxmail.com
 * Date:  2018/08/28
 * Time:  21:40
 * Desc:  后台必须登录才能访问的控制器基类
 */

namespace backend\controllers;

use Yii;

class AdminController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (Yii::$app->user->isGuest) {
            $this->goLogin();
        }
    }

}