<?php
/**
 * User:  jiangm
 * Email: jmphper@foxmail.com
 * Date:  2018/08/28
 * Time:  21:39
 * Desc:  后台登录
 */

namespace backend\controllers;

use Yii;
use backend\models\Admin;

class LoginController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 登录
     * @return string|\yii\web\Response
     */
    public function actionIndex()
    {
        $this->layout = false;
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new Admin();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * 退出登录
     */
    public function actionOut()
    {
        Yii::$app->user->logout();
        return $this->goLogin();
    }
    
}