<?php
/**
 * Author: jiangm
 * Email: jmphper@foxmail.com
 * Date: 2018/8/31
 * Time: 16:50
 * Desc: 项目基础模型
 */

namespace common\models;

use Yii;
use yii\base\Model;

class BaseModel extends Model
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 获取一条错误信息
     * @return string
     */
    public function getFirstErrorOne()
    {
        if(!$this->getFirstErrors()) return '';
        return current($this->getFirstErrors());
    }
}