<?php
/**
 * Author: jiangm
 * Email: jmphper@foxmail.com
 * Date: 2018/8/16
 * Time: 11:56
 * Desc: 后台用户模型
 */

namespace backend\models;

use Yii;

class Admin extends \common\models\Admin
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


}